using System.Security.Cryptography;
using AuthServer.Data;
using AuthServer.Options;
using AuthServer.Services.Cryptography;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using OpenIddict.Server;

namespace AuthServer.Services.SigningKeys;

/// <summary>
/// Provides open iddict signing credentials configurator functionality.
/// </summary>
public sealed class OpenIddictSigningCredentialsConfigurator : IConfigureOptions<OpenIddictServerOptions>
{
    private readonly IServiceProvider _serviceProvider;

    public OpenIddictSigningCredentialsConfigurator(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    public void Configure(OpenIddictServerOptions options)
    {
        using var scope = _serviceProvider.CreateScope();
        var keyRing = scope.ServiceProvider.GetRequiredService<SigningKeyRingService>();
        var signingOptions = scope.ServiceProvider.GetRequiredService<IOptionsMonitor<AuthServerSigningKeyOptions>>();
        var certificateOptions = scope.ServiceProvider.GetRequiredService<IOptions<AuthServerCertificateOptions>>();
        var environment = scope.ServiceProvider.GetRequiredService<IHostEnvironment>();
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<OpenIddictSigningCredentialsConfigurator>>();
        var mode = SigningKeyModeResolver.Resolve(signingOptions.CurrentValue.Mode, environment);

        // IMPORTANT: JWKS is generated by OpenIddict from the configured signing keys/credentials.
        // OpenIddict 7.2.0 doesn't expose OpenIddictServerOptions.JsonWebKeySet.
        options.SigningCredentials.Clear();

        if (mode == SigningKeyMode.Certificates)
        {
            var configured = ConfigureCertificateSigning(options, signingOptions.CurrentValue, certificateOptions.Value);
            if (configured)
            {
                return;
            }
        }

        ConfigureDbKeyRingSigning(options, keyRing, logger);
    }

    private static bool ConfigureCertificateSigning(
        OpenIddictServerOptions options,
        AuthServerSigningKeyOptions signingOptions,
        AuthServerCertificateOptions certificateOptions)
    {
        var certificate = CertificateLoader.TryLoadCertificate(certificateOptions.Signing);
        if (certificate is null)
        {
            throw new InvalidOperationException("Signing certificate is required when SigningKeys:Mode is Certificates.");
        }

        var key = new X509SecurityKey(certificate)
        {
            KeyId = Base64UrlEncoder.Encode(certificate.GetCertHash())
        };

        // Active key = first credential (preferred for signing).
        options.SigningCredentials.Add(new SigningCredentials(key, signingOptions.Algorithm));
        return true;
    }

    private static void ConfigureDbKeyRingSigning(
        OpenIddictServerOptions options,
        SigningKeyRingService keyRing,
        ILogger logger)
    {
        var keys = keyRing.GetCurrentAsync(CancellationToken.None).GetAwaiter().GetResult();
        if (keys.Count == 0)
        {
            var active = keyRing.EnsureInitializedAsync(CancellationToken.None).GetAwaiter().GetResult();
            keys = new List<SigningKeyRingEntry> { active };
        }

        // We want deterministic ordering:
        // 1) Active first (used to sign)
        // 2) Previous second (published in JWKS via credentials, but not preferred for signing)
        var ordered = keys
            .OrderBy(entry => entry.Status == SigningKeyStatus.Active ? 0 :
                              entry.Status == SigningKeyStatus.Previous ? 1 : 2)
            .ThenByDescending(entry => entry.ActivatedUtc ?? entry.CreatedUtc)
            .ThenBy(entry => entry.Kid, StringComparer.Ordinal)
            .ToList();

        var activeEntry = ordered.FirstOrDefault(entry => entry.Status == SigningKeyStatus.Active);
        var activeAdded = false;
        var activeFailed = false;

        if (activeEntry is not null)
        {
            try
            {
                options.SigningCredentials.Add(keyRing.CreateSigningCredentials(activeEntry));
                activeAdded = true;
            }
            catch (CryptographicException ex)
            {
                logger.LogError(ex, "Failed to unprotect signing key material for {Kid}.", activeEntry.Kid);
                activeFailed = true;
            }
        }

        if (!activeAdded)
        {
            if (activeEntry is not null && activeFailed)
            {
                keyRing.RevokeAsync(activeEntry.Kid, CancellationToken.None).GetAwaiter().GetResult();

                var refreshedActive = keyRing.GetActiveAsync(CancellationToken.None).GetAwaiter().GetResult()
                    ?? keyRing.EnsureInitializedAsync(CancellationToken.None).GetAwaiter().GetResult();

                options.SigningCredentials.Add(keyRing.CreateSigningCredentials(refreshedActive));
                logger.LogWarning("Rotated signing key after failing to unprotect the active key material.");
            }
            else if (options.SigningCredentials.Count == 0)
            {
                var refreshedActive = keyRing.EnsureInitializedAsync(CancellationToken.None).GetAwaiter().GetResult();
                options.SigningCredentials.Add(keyRing.CreateSigningCredentials(refreshedActive));
                logger.LogWarning("Initialized a new signing key because none could be loaded.");
            }
        }

        // Add the remaining keys (e.g., Previous) so JWKS can expose them for rollover validation.
        foreach (var entry in ordered)
        {
            if (activeEntry is not null && entry.Kid == activeEntry.Kid)
                continue;

            if (entry.Status is SigningKeyStatus.Previous)
            {
                try
                {
                    options.SigningCredentials.Add(keyRing.CreateSigningCredentials(entry));
                }
                catch (CryptographicException ex)
                {
                    if (TryAddPublicSigningCredential(options, entry, logger))
                    {
                        logger.LogWarning(ex, "Failed to unprotect previous signing key material for {Kid}. Falling back to public JWK publication.", entry.Kid);
                    }
                }
            }
        }
    }

    private static bool TryAddPublicSigningCredential(
        OpenIddictServerOptions options,
        SigningKeyRingEntry entry,
        ILogger logger)
    {
        if (string.IsNullOrWhiteSpace(entry.PublicJwkJson))
        {
            logger.LogWarning("Previous signing key {Kid} has no stored public JWK and cannot be published for rollover.", entry.Kid);
            return false;
        }

        try
        {
            var key = new JsonWebKey(entry.PublicJwkJson);
            options.SigningCredentials.Add(new SigningCredentials(key, entry.Algorithm));
            return true;
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Stored public JWK for signing key {Kid} could not be parsed.", entry.Kid);
            return false;
        }
    }
}
