\connect astra
GRANT CONNECT ON DATABASE astra TO astra_app;
GRANT USAGE ON SCHEMA public TO astra_app;
GRANT USAGE ON SCHEMA app TO astra_app;
ALTER DEFAULT PRIVILEGES FOR ROLE astra_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO astra_app;
ALTER DEFAULT PRIVILEGES FOR ROLE astra_owner IN SCHEMA app GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO astra_app;
ALTER DEFAULT PRIVILEGES FOR ROLE astra_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO astra_app;
ALTER DEFAULT PRIVILEGES FOR ROLE astra_owner IN SCHEMA app GRANT USAGE, SELECT ON SEQUENCES TO astra_app;
